### ISSUE TITLE
nc大

### ISSUE THREAD

**Issue by wwyqianqian** [tyan-boot/NcuLibrary#1]
为你的ncu搞图书检索咩 fighting！

**Comment by tyan-boot** [comment]
…算是第四次作业吧。

2016年11月13日 23:55，wwyqianqian notifications@github.com写道：

为你的ncu搞图书检索咩 fighting！

**Comment by wwyqianqian** [comment]
厉害了，我的b哥（你们学校作业真是可怕（逃···今天加了家园工作室鹅号，关注一波2333

**Comment by tyan-boot** [comment]
这都可以。这其实是开发部的第四次作业。。。学校哪有这么快的进度

**Comment by wwyqianqian** [comment]
恩恩！！刚入学开发部作业都这样6，新人都得一脸懵233
